"""add rejected field to products

Revision ID: 03864f55bf44
Revises: e0a349d26227
Create Date: 2025-05-07 23:05:40.157750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03864f55bf44'
down_revision = 'e0a349d26227'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rejected', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('rejected')

    # ### end Alembic commands ###
