"""Ensure relationships and cascade settings are in sync

Revision ID: 3184982d1e09
Revises: 32a7f9357764
Create Date: 2025-04-24 22:45:53.681267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3184982d1e09'
down_revision = '32a7f9357764'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_categories', schema=None) as batch_op:
        batch_op.drop_constraint('product_categories_category_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('product_categories_product_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'])
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('product_categories_product_id_fkey', 'products', ['product_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('product_categories_category_id_fkey', 'categories', ['category_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
