"""Fix overlaps and cascade delete in ProductCategories

Revision ID: 32a7f9357764
Revises: 929d06ed1085
Create Date: 2025-04-24 22:20:35.421268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32a7f9357764'
down_revision = '929d06ed1085'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_categories', schema=None) as batch_op:
        batch_op.drop_constraint('product_categories_product_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('product_categories_category_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('product_categories_category_id_fkey', 'categories', ['category_id'], ['id'])
        batch_op.create_foreign_key('product_categories_product_id_fkey', 'products', ['product_id'], ['id'])

    # ### end Alembic commands ###
