"""Make vendor_id NOT NULL after data update

Revision ID: 8919222d0149
Revises: e1a48774c7df
Create Date: 2025-04-26 23:25:51.557702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8919222d0149'
down_revision = 'e1a48774c7df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.alter_column('vendor_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.alter_column('vendor_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
