"""Update Models users scheme nullable settings

Revision ID: e0a349d26227
Revises: 3ca21b256ffa
Create Date: 2025-05-01 19:23:14.061672

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e0a349d26227'
down_revision = '3ca21b256ffa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_number', sa.String(length=20), nullable=True))
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('date_of_birth',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('zip_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('customer', 'vendor', 'admin', name='roletype'),
               nullable=True)
        batch_op.alter_column('bank_account',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('bank_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('bank_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('bank_account',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('customer', 'vendor', 'admin', name='roletype'),
               nullable=False)
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('zip_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('date_of_birth',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('account_number')

    # ### end Alembic commands ###
