"""Add vendor_id to order_items

Revision ID: e1a48774c7df
Revises: 3184982d1e09
Create Date: 2025-04-26 23:18:27.900314

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e1a48774c7df"
down_revision = "3184982d1e09"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("order_items", schema=None) as batch_op:
        batch_op.add_column(sa.Column("vendor_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, "users", ["vendor_id"], ["id"])

    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.drop_column("location")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "location", sa.VARCHAR(length=120), autoincrement=False, nullable=True
            )
        )

    with op.batch_alter_table("order_items", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("vendor_id")

    # ### end Alembic commands ###
